# build sphinx

name: Sphinx build and deploy

on:
  workflow_dispatch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.14.2"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt
    - name: Build Sphinx for Github Pages
      run: |
        rm -rf ./docs
        sphinx-build -b html source docs
    - name: Create .nojekyll
      run: |
        touch ./docs/.nojekyll
    - name: Commit and push changes
      run: |
        git config --global user.name "687 Autobuild"
        git config --global user.email "nerdherd@users.noreply.github.com"
        git add ./.
        git commit -m "Build latest version"
        git push
    - name: Build github pages
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: pages.yml
